"""
alembic/env.py — Alembic migration environment.

This file is auto-generated by `alembic init` and customized to:
  1. Read the database URL from our app's settings (not a hardcoded string)
  2. Import all ORM models so Alembic can detect schema changes
  3. Support both online (against live DB) and offline (SQL script) modes
"""
from logging.config import fileConfig
from sqlalchemy import engine_from_config, pool
from alembic import context

# ── Import app config and all models ─────────────────────────────────────────
# These imports must happen BEFORE `target_metadata = Base.metadata`
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from app.core.config import settings
from app.db.base import Base
from app.models import User, Role, Permission, Document  # Register all models

# ── Alembic Config ─────────────────────────────────────────────────────────────
config = context.config

# Override the sqlalchemy.url in alembic.ini with our env var
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Set up Python logging from alembic.ini (optional)
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# target_metadata tells Alembic what the schema SHOULD look like
# It compares this against the actual DB to generate migration scripts
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations without a live database connection.
    Generates SQL scripts to apply manually.
    Useful for reviewing changes before applying them.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations against a live database connection.
    This is the mode used in normal development/deployment.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # NullPool is best for migrations (no pooling)
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


# Alembic calls either function depending on the --sql flag
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
